<?xml version="1.0"?>

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro" name="h4r_farmbot">
    
    <xacro:include filename="$(find h4r_rapid_robot_xacros)/def/rapid_robot.xacro"/>
    <xacro:include filename="$(find h4r_farmbot_descriptions)/def/farmbot/frame.xacro"/>
    <xacro:include filename="$(find h4r_farmbot_descriptions)/def/farmbot/properties.xacro"/>
    <xacro:include filename="$(find h4r_farmbot_descriptions)/def/farmbot/bed.xacro"/>
    <xacro:include filename="$(find h4r_farmbot_descriptions)/def/farmbot/rails.xacro"/>
    <xacro:include filename="$(find h4r_farmbot_descriptions)/def/farmbot/boom.xacro"/>
    <xacro:include filename="$(find h4r_farmbot_descriptions)/def/farmbot/vertical.xacro"/>
    
    <!-- UTM -->
    <xacro:rr_joint_fixed parent="vertical" child="utm" origin_y="0.0465" origin_z="${-vertical_length/2+0.002}" origin_Y="${-rr_const_pi/2}" /> 
    <xacro:include filename="$(find h4r_farmbot_descriptions)/def/farmbot/utm.xacro"/>
    
   
    <xacro:include filename="$(find h4r_farmbot_descriptions)/def/farmbot/toolbays.xacro"/>
    <xacro:include filename="$(find h4r_farmbot_descriptions)/def/common/magnet_group.xacro"/> 
   
    <!-- ROS CONTROL PLUGIN -->
    <xacro:rr_roscontrol_controller />
</robot>