<?xml version="1.0"?>

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">
	
   <xacro:rr_joint_fixed parent="vertical" child="utm" origin_z="${-vertical_length/2}" />		   	
   <xacro:arg name="mesh_version" default="v1.2" />
	<link name="utm">
		<visual>
			<geometry>
				 <mesh filename="package://h4r_farmbot_descriptions/mesh/$(arg mesh_version)/utm.stl"/>
			</geometry>
		
		</visual>
		
		<collision>
			<geometry>
				<cylinder length="0.1" radius="0.05" />
			</geometry>  	
		</collision>			      	

		
		<xacro:rr_inertia_cylinder_solid r="0.05" h="0.1" mass="0.25" >
			<origin xyz="0 0 0" rpy="0 0 0" />
		</xacro:rr_inertia_cylinder_solid>
	</link>	
       	
</robot>